server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_FILE=4
    user: test_db
    password: test_db
    clean-on-validation-error: true
    baseline-on-migrate: true
    clean-disabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true